### ISSUE TITLE
Typo in JSX of Order component

### ISSUE THREAD

**Issue by Moussa-Kalam** [btholt/complete-intro-to-react-v9#5]
### Typo in JSX of **Order** Component

**Description**
There’s a typo in the JSX for the `Order.jsx` component. Currently, it displays `Pizza Type` as the label for `Pizza Size`.

**Steps to Reproduce**
1. Go to the `Order.jsx` component file.
2. Locate the second label.
<img width="557" alt="Screenshot 2024-11-01 at 07 54 51" src="https://github.com/user-attachments/assets/ab24e736-1a60-4ea2-8799-1273202ffbb7">

**Expected Code**
The `label` tag should display `Pizza Size` instead of `Pizza Type`.

**Comment by dtauer** [comment]
Thanks for catching this!

**Comment by Moussa-Kalam** [comment]
You're welcome
